language: node_js
node_js:
  - "9"
script:
  - yarn build:prod
deploy:
  provider: script
  script: bash upload.bash
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack: v2land:xoeT2IXt8yCaUfMxoBbXrSZD
