language: node_js
node_js:
  - "9"
script:
  - yarn build:prod
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "enderman-static"
  skip_cleanup: true
  local_dir: dist
  upload-dir: js
  on:
    branch: master
notifications:
  slack: v2land:xoeT2IXt8yCaUfMxoBbXrSZD
